version: 2.1

jobs:
  print_hello:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - run:
          name: "Say hello"
          command: "echo Hello, World!"
  build-frontend:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - restore_cache:
          keys: [frontend-build]
      - run:
          name: Build front-end
          command: |
            cd frontend
            npm install
            npm run build
      - save_cache:
          paths: [frontend/node_modules]
          key: frontend-build
  build-backend:
      docker:
        - image: circleci/node:13.8.0
      steps:
        - checkout
        - restore_cache:
            keys: [backend-build]
        - run:
            name: Back-end build
            command: |
              cd backend
              npm install
        - save_cache:
            paths: [backend/node_modules]
            key: backend-build
  test-frontend:
        docker:
          - image: circleci/node:13.8.0
        steps:
          - checkout
          - restore_cache:
              keys: [frontend-build]
          - run:
              name: tests for front end
              command: |
                cd frontend
                npm install
                npm run test
  test-backend:
          docker:
            - image: circleci/node:13.8.0
          steps:
            - checkout
            - restore_cache:
                keys: [backend-build]
            - run:
                name: tests for back end
                command: |
                  cd backend
                  npm install
                  npm run test
  scan-frontend:
        docker:
          - image: circleci/node:13.8.0
        steps:
          - checkout
          - restore_cache:
              keys: [frontend-build]
          - run:
              name: analyze front end vulnerabilities
              command: |
                cd frontend
                npm install
                npm audit --audit-level=critical
  scan-backend:
        docker:
          - image: circleci/node:13.8.0
        steps:
          - checkout
          - restore_cache:
              keys: [backend-build]
          - run:
              name: analyze back end vulnerabilities
              command: |
                cd backend
                npm install
                npm audit --audit-level=critical
           
workflows:
  default:
    jobs:
      - print_hello
      - build-frontend
      - test-frontend:
          requires: [build-frontend]
      - scan-frontend:
          requires: [build-frontend]      
      - build-backend
      - test-backend:
          requires: [build-backend]
      - scan-backend:
          requires: [build-backend] 